experiment_name: keras_tuner_fully_connected_pipeline_2
input_files:
    app: "hyperparameter_tuning_custom_training.py"
    models: models/model_cnn.py
    dataset: datasets/data_loader_classification.py 

training_config:
    epochs: 5
    max_trials: 5
  
